### PR TITLE
Merge multipart uploads

### PR DESCRIPTION
**Pull request by Scylardor**
I implemented the multipart uploads in tinys3, I currently use them in my application and they work well.

A quick tour on how to use them if you would like to test: 

- Create a multipart upload: 
```
co = tinys3.Connection('key', 'secret', 'bucket', tls=True)
mp_upload = co.initiate_multipart_upload(key='test', bucket='bucket')  # bucket is optional
```

`initiate_multipart_upload` returns a MultipartUpload object bound to the connection it comes from, and it works quite like the Boto one.

- Upload a part:
```
resp = mp_upload.upload_part_from_file(fp, 1)
```

`upload_part_from_file` returns the requests response. It can take a length and md5 parameters that will be put in the request's `Content-Length` and `Content-MD5` headers, and also the file handling parameters (close, rewind) UploadRequest already takes and that do the same thing.

- Complete the upload:
```
resp = mp_upload.complete_upload()
```

`complete_upload` returns the requests response. 

- Abort the upload:
```
mp_upload.cancel_upload()
```
`cancel_upload` returns the requests response. 

- List a bucket's multipart uploads: 
```
for mp in co.list_multipart_uploads(bucket='bucket'):
    print mp.bucket, mp.key, mp.uploadId
```
`list_multipart_uploads` can also take a `prefix` parameter to list only multipart uploads that concern files under a specified directory.

- List a multipart upload's already uploaded parts:
```
for p in mp.list_parts():
    print p['part_number'], p['last_modified'], p['size'], p['etag']
```

However, I also made a number of changes in the rest of the project, here are some notes : 

- Since I tried as much as possible to comply to PEP8, a lot of formatting has changed. I hope it won't bother (but PEP8 compliance is cool)

- I updated of the AWS_QUERY_PARAMS for multipart upload requests to work

- It turned out that sorting the query string keys in low-level request signature method was necessary

- I changed all the format strings from the "str % format" version to string.format version

- Since I need to use the GET request's Range header, I added an headers param to S3Connection.get()

- ~~Also added some parameters to the list function~~ (This was removed because it was making the tests fail, I don't use it, and I'm a bit lazy.)

- Created the XML_PARSE_STRING global as it is used at a lot of places in the code (more maintainable)

- Changed the request URL in bucket_url from region-based to virtual-hosting style

- I added the DeleteRequest and HeadRequest classes.

### CODE REVIEW

**Comment by aaronmfraser** [comment]
So i guess this is never going to be merged?

**Comment by shlomiatar** [comment]
Hi, sorry dude, I had an issue with my notifications so I never saw that :-/ 

Going over it right now...

**Comment by Scylardor** [comment]
Wow, this was quite a long time ago indeed.
It passed fine back then, but now there are merge conflicts. Plus, I just realized I didn't include tests for the new features...

Shlomi, I'm sorry this is a rather big PR, but as soon as you're finished overviewing it, just share your impressions and I'll do the fix ASAP. I'll also add tests to it.

**Comment by aaronmfraser** [comment]
If I can help in anyway, I'd love to. I'll be using this quite a bit to manage large hprof files. I am about to write my own library as I need to make some traction.

**Comment by Scylardor** [comment]
Hello,

so I finally got to finish this... Now with tests !

I also removed a dependency on the MultipartUpload object from some of the requests to keep a similar interface between all requests, along other minor changes. 

I also tried to be as PEP8 compliant as possible.

**Pull request merged**
